### ISSUE TITLE
Nothing wrong

### ISSUE THREAD

**Issue by spotdemo4** [nstringham/COSC314-Our-First-Computer-Project#2]
This is a neat little program. Nothing immediately pops out in terms of improvement, nice work!

**Comment by nstringham** [comment]
> This is a neat little program. Nothing immediately pops out in terms of improvement, nice work!

Thanks

**Comment by nstringham** [comment]
@spotdemo4 I think he changed the assignment instructions so that you are required to make a PR. You can just add a comment or something. I wouldn't want you to loose points.
